---
# tasks file for locales

# https://stackoverflow.com/questions/52421542/ansible-debconf-module-not-working-properly-to-set-default-locale
# So for now we use locale_gen module to generate locales and a template to replace the default locale in /etc/default/locale

- name: generate
  locale_gen:
    name: '{{ item }}'
    state: present
  loop: "{{ locales_to_be_generated }}"
  when: locales_to_be_generated is defined
  tags:
    - locales
    - gen

- name: default
  template:
    src: default.j2
    dest: /etc/default/locale
  when: locales_default is defined
  tags:
    - locales
    - default
...
