---
# tasks file for locales

# https://stackoverflow.com/questions/52421542/ansible-debconf-module-not-working-properly-to-set-default-locale
#
# So for now we use locale_gen module to generate locales and a template to
# replace the default locale in /etc/default/locale

- name: package
  package:
    name: locales
  tags:
    - locales
    - package

- name: generate
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ locale_gen }}"
  when: locale_gen is defined
  tags:
    - locales
    - gen

- name: default
  template:
    src: default.j2
    dest: /etc/default/locale
    mode: 0644
  when: locale_default is defined
  tags:
    - locales
    - default
